spring.application.name=movieticketingservicenew

server.port = 8080

spring.datasource.url=jdbc:postgresql://localhost:5432/movieticketingdb
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.elasticsearch.uris=http://localhost:9200

spring.data.elasticsearch.repositories.enabled=true
spring.elasticsearch.rest.enable-auto-index=false
spring.jackson.serialization.write-dates-as-timestamps=false

jwt.secret=8f7d2a9c5e4b1f3a7d8c6e2f9b4a1d5c7e8f3b6a2d9c4e7f1a5b8d3c6e9f2a4
jwt.expiration = 360000