spring.application.name=movieticketingservicenew

server.port = 8080

spring.datasource.url=jdbc:postgresql://localhost:5432/movieticketingdb
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.elasticsearch.uris=http://localhost:9200

spring.data.elasticsearch.repositories.enabled=true
spring.elasticsearch.rest.enable-auto-index=false
spring.jackson.serialization.write-dates-as-timestamps=false

jwt.secret=${JWT_SECRET}
jwt.expiration = 86400000

spring.profiles.default=dev

app.cors.allowed-origins=http://localhost:3000,http://localhost:5173

graphify.base-url=http://localhost:7474/service/graphify